---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: create /opt/bin directory
      file:
        path: /opt/bin
        state: directory
        owner: root
        group: root
        mode: 0775
    - name: reflector sync script
      copy:
        content: |
          #!/bin/sh
          reflector --verbose --latest 40 --number 10 --sort rate --protocol https --save /etc/pacman.d/mirrorlist
        dest: /opt/bin/reflector_sync.sh
        mode: +x
    - name: pacman hooks
      copy:
        content: |
          [Trigger]
          Type = Package
          Operation = Install
          Operation = Upgrade
          Target = pacman-mirrorlist

          [Action]
          Description = Updating mirrorlist...
          When = PostTransaction
          Depends = reflector
          Exec = /opt/bin/reflector_sync.sh
        dest: /etc/pacman.d/hooks/reflector_sync.hook
    - name: update mirrorlist
      pacman:
        name:
          - pacman-mirrorlist
    - name: full upgrade
      pacman:
        update_cache: true
        upgrade: true
    - name: install must-have packages
      pacman:
        name:
          - arch-install-scripts
          - chromium
          - netdata
          - reflector
          - tmux
          - xscreensaver
    - name: install development packages
      pacman:
        name:
          - base-devel
          - cmake
          - docker
          - docker-compose
          - docker-machine
          - gdb
          - hub
          - inotify-tools
          - neovim
          - thefuck
          - valgrind
    - name: install useful utilities
      pacman:
        name:
          - arch-audit
          - gnome-keyring
          - gnome-screenshot
          - gparted
          - moreutils
          - pavucontrol
          - unrar
          - zip
